from transport import *
c=Client(); guest=Client()
check('Installer rejects incorrect setup key',c.setup('incorrect')[0]==403)
code,body=c.setup('local-test-setup-key')
check('Installer creates schema and first account',code==200 and 'สร้างบัญชีเรียบร้อยแล้ว' in body)
check('Installer cannot create a second initial account',c.setup('local-test-setup-key')[0]==409)
check('Health connects to MariaDB',c.call('health')==(200,{'ok':True,'backend':'php'}))
check('Unauthenticated admin denied',guest.call('admin/news')[0]==401)
check('Anonymous auth returns csrf token',c.call('auth/me')[1]['user'] is None and bool(c.csrf))
check('Login requires CSRF',c.call('auth/login','POST',{'username':'owner','password':'Owner-Password-2026'},csrf=False)[0]==403)
check('Cross-site request denied',c.call('auth/login','POST',{'username':'owner','password':'Owner-Password-2026'},headers={'Origin':'https://evil.example'})[0]==403)
check('Wrong password clearly rejected',c.call('auth/login','POST',{'username':'owner','password':'wrong'})[0]==401)
old=c.csrf
code,body=c.call('auth/login','POST',{'username':'owner','password':'Owner-Password-2026'})
check('Login succeeds and rotates CSRF',code==200 and body['user']['username']=='owner' and old!=c.csrf)
pair=lambda s:{'th':s,'en':s}
news=dict(slug='integration-news',title=pair('ข่าวทดสอบ'),excerpt=pair('รายละเอียด'),body=pair('เนื้อหา'),category='company',publishedAt='2026-01-01T00:00:00.000Z',status='draft',featured=False,cover=None)
code,body=c.call('admin/news','POST',news); nid=body.get('id')
check('News create bilingual draft',code==201 and nid)
check('Draft news hidden from public',guest.call('news')[1]==[])
check('Unchanged news update works',c.call(f'admin/news/{nid}','PUT',news)[0]==200)
news['status']='published'; news['publishedAt']='2099-01-01T00:00:00.000Z'
check('Future news save works',c.call(f'admin/news/{nid}','PUT',news)[0]==200)
check('Scheduled future news hidden',guest.call('news')[1]==[])
news['publishedAt']='2026-01-01T00:00:00.000Z'
check('Published news update works',c.call(f'admin/news/{nid}','PUT',news)[0]==200)
check('Published news available by slug',guest.call('news/integration-news')[1]['title']==news['title'])
check('Duplicate slug returns conflict',c.call('admin/news','POST',news)[0]==409)
invalid=copy.deepcopy(news); invalid['title']['en']=''
check('Missing second language rejected',c.call(f'admin/news/{nid}','PUT',invalid)[0]==400)
ref=dict(name=pair('หน้างาน'),customer=pair('ลูกค้า'),location=pair('ระยอง'),position=3,status='draft',image=None)
code,body=c.call('admin/site-references','POST',ref); rid=body.get('id')
check('Site reference create',code==201 and rid)
check('Draft reference hidden',guest.call('site-references')[1]==[])
ref['status']='published'
check('Reference publish works',c.call(f'admin/site-references/{rid}','PUT',ref)[0]==200)
check('Public reference shape and order',guest.call('site-references')[1][0]['name']==ref['name'])
project=dict(slug='integration-project',name=pair('งานทดสอบ'),client=pair('ลูกค้า'),location=pair('ระยอง'),industry='chemical',year=2026,overview=pair('ภาพรวม'),engineeringSolution=pair('ระบบสื่อสาร'),scopeOfWork=[pair('ติดตั้ง'),pair('ทดสอบ')],gallery=[],cover=None,featured=False,status='published')
code,body=c.call('admin/projects','POST',project); pid=body.get('id')
check('Project and ordered scope save',code==201 and pid)
check('Public project reads children',guest.call('projects/integration-project')[1]['scopeOfWork']==project['scopeOfWork'])
broken=copy.deepcopy(project); broken['name']=pair('Must rollback'); broken['scopeOfWork'][1]['en']=''
check('Invalid child rejected',c.call(f'admin/projects/{pid}','PUT',broken)[0]==400)
check('Parent and children rollback atomically',c.call(f'admin/projects/{pid}')[1]['name']==project['name'] and c.call(f'admin/projects/{pid}')[1]['scopeOfWork']==project['scopeOfWork'])
def png(w,h):
    def chunk(t,v): return struct.pack('!I',len(v))+t+v+struct.pack('!I',zlib.crc32(t+v)&0xffffffff)
    return b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('!2I5B',w,h,8,2,0,0,0))+chunk(b'IDAT',zlib.compress((b'\0'+b'\x00\x40\xff'*w)*h))+chunk(b'IEND',b'')
def upload(client,content,name='photo.png'):
    boundary='idieTestBoundary'
    raw=(f'--{boundary}\r\nContent-Disposition: form-data; name="file"; filename="{name}"\r\nContent-Type: image/png\r\n\r\n'.encode()+content+f'\r\n--{boundary}--\r\n'.encode())
    return client.call('admin/uploads','POST',raw=raw,headers={'Content-Type':'multipart/form-data; boundary='+boundary})
check('Upload requires login',upload(guest,png(10,10))[0]==401)
check('SVG disguised as PNG rejected',upload(c,b'<svg xmlns="http://www.w3.org/2000/svg"/>')[0]==400)
check('Oversized upload rejected',upload(c,b'x'*3000001)[0]==413)
code,img=upload(c,png(1600,800))
check('Image reencoded and resized',code==201 and img['width']==1400 and img['height']==700 and '700w' in img['srcSet'])
check('Uploaded image accessible',c.opener.open(BASE+img['src']).status==200)
asset=dict(img,alt=pair('ภาพหน้างาน'))
project['cover']=asset; project['gallery']=[asset]
check('Project gallery stores uploaded assets',c.call(f'admin/projects/{pid}','PUT',project)[0]==200 and guest.call('projects/integration-project')[1]['gallery'][0]['src']==img['src'])
bad=copy.deepcopy(news); bad['cover']={'src':'https://evil.example/x.png','alt':pair('X')}
check('Foreign image paths rejected',c.call(f'admin/news/{nid}','PUT',bad)[0]==400)
code,body=c.call('admin/users','POST',{'username':'editor','displayName':'Editor','password':'Editor-Password-2026'}); uid=body.get('id')
check('Create second admin account',code==201 and uid)
editor=Client()
check('Second admin login',editor.call('auth/login','POST',{'username':'editor','password':'Editor-Password-2026'})[0]==200)
check('Password reset for another account',c.call(f'admin/users/{uid}/password','POST',{'newPassword':'New-Editor-Password-2026'})[0]==200)
check('Password reset revokes previous session',editor.call('admin/news')[0]==401)
check('Cannot delete own account',c.call('admin/users/1','DELETE')[0]==400)
check('Own password requires current password',c.call('admin/users/1/password','POST',{'newPassword':'New-Owner-Password-2026'})[0]==400)
check('Own password change works',c.call('admin/users/me/password','POST',{'currentPassword':'Owner-Password-2026','newPassword':'New-Owner-Password-2026'})[0]==200)
check('Own renewed session remains valid',c.call('admin/news')[0]==200)
inquiry=dict(name='Integration Test',email='person@example.com',subject='Test',message='No real recipient',locale='en')
bad=copy.deepcopy(inquiry); bad['email']='invalid'
check('Inquiry email validation',guest.call('contact','POST',bad)[0]==400)
check('Honeypot discarded',guest.call('contact','POST',{'website':'bot'})==(200,{'ok':True}))
check('Missing SMTP never pretends delivery',guest.call('contact','POST',inquiry)[0]==503)
before=guest.call('visitors')[1]['total']
check('Visitor count increments once',guest.call('visitors','POST')[1]['total']==before+1)
check('Visitor cookie prevents duplicates',guest.call('visitors','POST')[1]['total']==before+1)
check('Reference deletion',c.call(f'admin/site-references/{rid}','DELETE')[0]==200 and guest.call('site-references')[1]==[])
check('Project deletion',c.call(f'admin/projects/{pid}','DELETE')[0]==200 and guest.call('projects')[1]==[])
check('News deletion',c.call(f'admin/news/{nid}','DELETE')[0]==200 and guest.call('news')[1]==[])
check('Logout ends authentication',c.call('auth/logout','POST')[0]==200 and c.call('admin/news')[0]==401)
for label in passed: print('PASS',label)
print(f'{len(passed)} integration checks passed')
Path('tmp/php-test/results.json').write_text(json.dumps(passed,ensure_ascii=False,indent=2),encoding='utf-8')